Found existing installation: setuptools 56.0.0
Uninstalling setuptools-56.0.0:
  Successfully uninstalled setuptools-56.0.0
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-57.4.0 wheel-0.36.2
WARNING: You are using pip version 21.1.3; however, version 21.2.3 is available.
You should consider upgrading via the '/tmp/build-env-a47bs81g/bin/python -m pip install --upgrade pip' command.
running egg_info
creating src/build_attr_bug.egg-info
writing src/build_attr_bug.egg-info/PKG-INFO
writing dependency_links to src/build_attr_bug.egg-info/dependency_links.txt
writing top-level names to src/build_attr_bug.egg-info/top_level.txt
writing manifest file 'src/build_attr_bug.egg-info/SOURCES.txt'
reading manifest file 'src/build_attr_bug.egg-info/SOURCES.txt'
writing manifest file 'src/build_attr_bug.egg-info/SOURCES.txt'
running sdist
running egg_info
writing src/build_attr_bug.egg-info/PKG-INFO
writing dependency_links to src/build_attr_bug.egg-info/dependency_links.txt
writing top-level names to src/build_attr_bug.egg-info/top_level.txt
reading manifest file 'src/build_attr_bug.egg-info/SOURCES.txt'
writing manifest file 'src/build_attr_bug.egg-info/SOURCES.txt'
running check
warning: check: missing required meta-data: url

creating build_attr_bug-0.1
creating build_attr_bug-0.1/src
creating build_attr_bug-0.1/src/build_attr_bug.egg-info
copying files to build_attr_bug-0.1...
copying README.md -> build_attr_bug-0.1
copying pyproject.toml -> build_attr_bug-0.1
copying setup.cfg -> build_attr_bug-0.1
copying src/build_attr_bug.egg-info/PKG-INFO -> build_attr_bug-0.1/src/build_attr_bug.egg-info
copying src/build_attr_bug.egg-info/SOURCES.txt -> build_attr_bug-0.1/src/build_attr_bug.egg-info
copying src/build_attr_bug.egg-info/dependency_links.txt -> build_attr_bug-0.1/src/build_attr_bug.egg-info
copying src/build_attr_bug.egg-info/top_level.txt -> build_attr_bug-0.1/src/build_attr_bug.egg-info
Writing build_attr_bug-0.1/setup.cfg
Creating tar archive
removing 'build_attr_bug-0.1' (and everything under it)
Found existing installation: setuptools 56.0.0
Uninstalling setuptools-56.0.0:
  Successfully uninstalled setuptools-56.0.0
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-57.4.0 wheel-0.36.2
WARNING: You are using pip version 21.1.3; however, version 21.2.3 is available.
You should consider upgrading via the '/tmp/build-env-5n3b2gk4/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/config.py", line 387, in _parse_attr
    return getattr(StaticModule(module_name), attr_name)
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/config.py", line 25, in __init__
    with open(spec.origin) as strm:
AttributeError: 'NoneType' object has no attribute 'origin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gian/python/build_attr_bug/venv_0.5.0/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 349, in <module>
    main()
  File "/home/gian/python/build_attr_bug/venv_0.5.0/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/gian/python/build_attr_bug/venv_0.5.0/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/dist.py", line 778, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/config.py", line 157, in parse_configuration
    meta.parse()
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/config.py", line 436, in parse_section
    self[name] = value
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/config.py", line 220, in __setitem__
    value = parser(value)
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/config.py", line 557, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/tmp/build-env-5n3b2gk4/lib/python3.9/site-packages/setuptools/config.py", line 390, in _parse_attr
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bug'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
